create database QLThuVien
use QLThuVien
drop table Sach
create table SACH
(
	MASACH varchar(10),
	TENSACH varchar(100),
	TACGIA varchar(100),
	NSX varchar(100),
	NXB int,
	NGAYNHAP date,
	GIA float,
	NVTIEPNHAN varchar(10),
	LOAI int,
	primary key (MASACH)
)
DROP TABLE DOCGIA
create table BANQUANLI
(
	MANV VARCHAR(10),
	HOTEN VARCHAR(100),
	DIACHI VARCHAR(100),
	SDT VARCHAR(20),
	DOB DATE,
	CMND VARCHAR(20),
	EMAIL VARCHAR(100),
	NGAYLAPTHE DATE,
	NVLAPTHE VARCHAR(10),
	BANGCAP VARCHAR(20),
	CHUCVU INT,
	PRIMARY KEY (MANV)
)

create table DOCGIA
(
	MADOCGIA VARCHAR(10),
	HOTEN VARCHAR(100),
	DIACHI VARCHAR(100),
	SDT VARCHAR(20),
	DOB DATE,
	CMND VARCHAR(20),
	EMAIL VARCHAR(100),
	NGAYLAPTHE DATE,
	NVLAPTHE VARCHAR(10),
	PRIMARY KEY (MADOCGIA)
)
DROP TABLE PHIEUMUON
DROP TABLE PHIEUTRA
DROP TABLE PHIEUMAT
CREATE TABLE PHIEUMUON
(
	MAPHIEUMUON VARCHAR(10),
	MADOCGIA VARCHAR(10),
	MASACH VARCHAR(10),
	NGAYMUON DATE,
	HANTRA DATE,
	PRIMARY KEY (MAPHIEUMUON)

)

CREATE TABLE PHIEUTRA
(
	MAPHIEUTRA VARCHAR(10),
	MADOCGIA VARCHAR(10),
	MASACH VARCHAR(10),
	NGAYTRA DATE,
	TIENPHAT FLOAT,
	PRIMARY KEY (MAPHIEUTRA)

)

CREATE TABLE PHIEUMAT
(
	MAPHIEUMAT VARCHAR(10),
	MADOCGIA VARCHAR(10),
	MASACH VARCHAR(10),
	NGAYGHINHAN DATE,
	TIENPHAT FLOAT,
	PRIMARY KEY (MAPHIEUMAT)

)
CREATE TABLE PHIEUTHU
(
	MAPHIEUTHU VARCHAR(10),
	MADOCGIA VARCHAR(10),
	MASACH VARCHAR(10),
	NGAYTHU DATE,
	TIENPHAT FLOAT,
	NVTHUTIEN VARCHAR(10),
	PRIMARY KEY (MAPHIEUTHU)
)

ALTER TABLE SACH
ADD CONSTRAINT FK_SACH_MANV
FOREIGN KEY (NVTIEPNHAN)
REFERENCES BANQUANLI(MANV);

ALTER TABLE DOCGIA
ADD CONSTRAINT FK_DOCGIA_MANV
FOREIGN KEY (NVLAPTHE)
REFERENCES BANQUANLI(MANV);

ALTER TABLE BANQUANLI
ADD CONSTRAINT FK_BANQUANLI_MANV
FOREIGN KEY (NVLAPTHE)
REFERENCES BANQUANLI(MANV);

ALTER TABLE PHIEUMUON
ADD CONSTRAINT FK_PHIEUMUON_MADOCGIA
FOREIGN KEY (MADOCGIA)
REFERENCES DOCGIA(MADOCGIA);

ALTER TABLE PHIEUMUON
ADD CONSTRAINT FK_PHIEUMUON_MASACH
FOREIGN KEY (MASACH)
REFERENCES SACH(MASACH);

ALTER TABLE PHIEUTRA
ADD CONSTRAINT FK_PHIEUTRA_MADOCGIA
FOREIGN KEY (MADOCGIA)
REFERENCES DOCGIA(MADOCGIA);

ALTER TABLE PHIEUTRA
ADD CONSTRAINT FK_PHIEUTRA_MASACH
FOREIGN KEY (MASACH)
REFERENCES SACH(MASACH);

ALTER TABLE PHIEUMAT
ADD CONSTRAINT FK_PHIEUMAT_MADOCGIA
FOREIGN KEY (MADOCGIA)
REFERENCES DOCGIA(MADOCGIA);

ALTER TABLE PHIEUMAT
ADD CONSTRAINT FK_PHIEUMAT_MASACH
FOREIGN KEY (MASACH)
REFERENCES SACH(MASACH);

ALTER TABLE PHIEUTHU
ADD CONSTRAINT FK_PHIEUTHU_MADOCGIA
FOREIGN KEY (MADOCGIA)
REFERENCES DOCGIA(MADOCGIA);

ALTER TABLE PHIEUTHU
ADD CONSTRAINT FK_PHIEUTHU_MASACH
FOREIGN KEY (MASACH)
REFERENCES SACH(MASACH);

ALTER TABLE PHIEUTHU
ADD CONSTRAINT FK_PHIEUTHU_MANV
FOREIGN KEY (NVTHUTIEN)
REFERENCES BANQUANLI(MANV);

insert into BANQUANLI(MANV,HOTEN,DIACHI,SDT,DOB,CMND,EMAIL,NGAYLAPTHE,NVLAPTHE,BANGCAP,CHUCVU) values ('1','Bao','190/19',
'0789578259','1998-8-5','0789578259','bao@gmail.com','2019-5-18','1','TienSi',0)

insert into SACH(MASACH,TENSACH,TACGIA,NSX,NXB,NGAYNHAP,GIA,NVTIEPNHAN,LOAI) values ('1','KinhVanHoa','NguyenNhatAnh','KimDong',
1990,'1990-01-02',120,'1',1)

select * from SACH